export class NotifyConst {
  //上线
  static NOTIFY_ONLINE = "NOTIFY_ONLINE"
  //异地登录
  static NOTIFY_REPEATED_LOGIN = "NOTIFY_REPEATED_LOGIN"
  //跑马灯
  static NOTIFY_MARQUEE_ARRIVED = "NOTIFY_MARQUEE_ARRIVED"
  //红点
  static NOTIFY_RED_DOT_UPDATE = "NOTIFY_RED_DOT_UPDATE"

  static NOTIFY_SOMEONE_JOIN = "NOTIFY_SOMEONE_JOIN";

  static NOTIFY_GAME_START = "NOTIFY_GAME_START";

  static NOTIFY_SOMEONE_READY = "NOTIFY_SOMEONE_READY";

  static NOTIFY_SOMEONE_QIANGZHUANG = "NOTIFY_SOMEONE_QIANGZHUANG";

  static NOTIFY_SOMEONE_EXIT_ROOM = "NOTIFY_SOMEONE_EXIT_ROOM"

  static NOTIFY_NOT_AUTH = "NOTIFY_NOT_AUTH";


  static NOTIFY_BIG_JACKPOT_CHANGE = "NOTIFY_BIG_JACKPOT_CHANGE"
}