# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'boost_container' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for boost_container

end

target 'cocos_engine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocos_engine

end

target '7k-slo-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'libOpenInstallSDK'
end
